/**
 * Workflow-authored Reading & Writing questions, grouped by skill.
 *
 * This file is GENERATED by `scripts/merge-rw-generated.ts` from batches authored
 * and adversarially verified by a multi-agent workflow, then balanced (choice
 * order shuffled for an even answer-key distribution) and de-duplicated against
 * the hand-authored bank. Do not edit by hand — re-run the merge instead.
 *
 * It is merged into the live bank by `lib/practice/rw-bank.ts` and validated by
 * `scripts/validate-rw-bank.ts`. Starts empty; the merge step fills it.
 */
import type { RWQuestion, RWSkillKey } from "../types";

export const GENERATED: Partial<Record<RWSkillKey, RWQuestion[]>> = {};
