export interface Lesson {
  id: string;
  title: string;
  tutor: string;
  durationSec: number;
  skill: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  description: string;
  thumbnail: string;
  /** Direct video URL when available. Falls back to an editorial "this drops next quarter" panel. */
  videoUrl?: string;
  /** Optional release hint shown in the fallback panel ("April 2026", "next quarter", etc.). */
  releaseHint?: string;
  takeaways: string[];
  transcript?: string;
}

export const LESSONS: Lesson[] = [
  {
    id: "sat-quad-1",
    title: "Quadratics: the discriminant trick",
    tutor: "Anika, Princeton '26",
    durationSec: 280,
    skill: "Algebra & functions",
    level: "Intermediate",
    description: "A 4-minute walkthrough of when the discriminant tells you the answer faster than factoring.",
    thumbnail: "/design/lesson-quadratics.jpg",
    takeaways: [
      "Read the discriminant b² − 4ac to know how many real solutions exist.",
      "Recognize the question patterns where the answer choices give it away.",
      "Skip factoring when the question only asks for the number of solutions.",
    ],
    transcript: "When you see ax² + bx + c = 0 and the question asks 'how many solutions does this equation have', factoring is the slow path. Compute b² − 4ac instead. Positive: two real roots. Zero: one. Negative: none.",
  },
  {
    id: "sat-rw-pacing",
    title: "Reading & Writing pacing under timer",
    tutor: "Ben, Yale '25",
    durationSec: 320,
    skill: "Pacing",
    level: "Beginner",
    description: "How to budget 53 seconds per question without rushing the long-passage questions.",
    thumbnail: "/design/lesson-pacing.jpg",
    takeaways: [
      "Spend 30 seconds on short-passage questions, 70 on long-passage.",
      "Check the clock at question 12, 22, and 32.",
      "Mark-and-skip at 75 seconds — never spend 90 on one question.",
    ],
  },
  {
    id: "act-science",
    title: "ACT Science: skim the chart, skip the prose",
    tutor: "Anika, Princeton '26",
    durationSec: 240,
    skill: "ACT Science strategy",
    level: "Beginner",
    description: "Most ACT Science questions are answerable from charts alone. Here's the order.",
    thumbnail: "/design/lesson-act-science.jpg",
    takeaways: [
      "Read the question first — find the variable.",
      "Locate the chart with that variable.",
      "Only read the prose if the chart leaves the answer ambiguous.",
    ],
  },
  {
    id: "essay-hook",
    title: "Personal statement: the first sentence",
    tutor: "Daniela, Stanford '24",
    durationSec: 360,
    skill: "Admissions essays",
    level: "Advanced",
    description: "Five hooks that work, two that don't, and how to pick yours.",
    thumbnail: "/design/lesson-essay.jpg",
    takeaways: [
      "Start with sensory specificity — sight, sound, smell.",
      "Avoid 'Ever since I was a child…' and dictionary openers.",
      "The first sentence's job is to earn the second.",
    ],
    transcript: "The first sentence has one job: earn the second. Don't try to compress your whole identity into it. Don't open with 'Ever since I was a child' or with a dictionary definition. The five hooks that work: sensory specificity, a strange small fact about yourself, a line of dialogue without setup, a claim you'll defend, or an action mid-motion. Pick one. Trust it.",
  },
  {
    id: "sat-systems",
    title: "Systems of equations: when to substitute, when to eliminate",
    tutor: "Anika, Princeton '26",
    durationSec: 300,
    skill: "Algebra & functions",
    level: "Intermediate",
    description: "Two methods, one scoring difference. The decision rule that picks the faster path.",
    thumbnail: "/design/lesson-systems.jpg",
    takeaways: [
      "If a variable has coefficient 1 in either equation, substitute.",
      "If both equations have aligned coefficients, eliminate.",
      "If the question asks for x + y or 2x − y, add or subtract directly — don't solve for each variable.",
    ],
    transcript: "Look at the system. Variable with coefficient 1? Substitute. Aligned coefficients? Eliminate. Question asks for x + y or a combination? Just add or subtract the equations directly. Three signals, three methods. Don't default to one.",
  },
  {
    id: "sat-quad-vertex",
    title: "Quadratics: vertex form in 30 seconds",
    tutor: "Anika, Princeton '26",
    durationSec: 240,
    skill: "Algebra & functions",
    level: "Advanced",
    description: "Convert any quadratic to vertex form without completing the square — the −b/(2a) shortcut.",
    thumbnail: "/design/lesson-vertex.jpg",
    takeaways: [
      "The x-coordinate of the vertex is always −b/(2a).",
      "Plug that x back into the original to get y.",
      "Skip completing the square unless the question explicitly demands the algebraic form.",
    ],
    transcript: "Completing the square is great math but slow. For SAT vertex questions, just compute x = −b/(2a). For y = 2x² − 8x + 5: x = 8/4 = 2; plug in: y = 8 − 16 + 5 = −3. Vertex (2, −3). Twenty seconds, no algebra.",
  },
  {
    id: "sat-rw-evidence",
    title: "Command of evidence: the substitution test",
    tutor: "Ben, Yale '25",
    durationSec: 320,
    skill: "Reading strategy",
    level: "Intermediate",
    description: "How to choose between two finalists on evidence questions without rereading.",
    thumbnail: "/design/lesson-evidence.jpg",
    takeaways: [
      "Read the blank and the sentence before it. Ignore the rest of the passage.",
      "Mentally substitute each finalist into the blank.",
      "Eliminate any choice that introduces a new claim or contradicts a stated fact.",
    ],
    transcript: "Most students reread the entire passage on evidence questions. Wrong move. The answer is determined by the sentence right before the blank. Read that sentence. Substitute each choice in. The right answer is the one whose claim is already implied by the surrounding text. The wrong answers always either contradict or introduce something new.",
  },
  {
    id: "sat-rw-transitions",
    title: "Transition words: contrast vs continuation",
    tutor: "Ben, Yale '25",
    durationSec: 220,
    skill: "Writing strategy",
    level: "Beginner",
    description: "The simplest framework for picking the right transition word every time.",
    thumbnail: "/design/lesson-transitions.jpg",
    takeaways: [
      "Read the sentence before AND after the transition.",
      "Agreement → continuation (also, furthermore). Disagreement → contrast (however, yet).",
      "Cause and effect → therefore, as a result.",
    ],
    transcript: "Transitions look hard until you reduce them to two buckets. Read the sentence before. Read the sentence after. Agree or disagree? Continuation: also, in addition, furthermore. Contrast: however, yet, nevertheless. Cause-effect: therefore, as a result. That covers 95% of SAT transitions.",
  },
  {
    id: "sat-rw-rhetorical",
    title: "Rhetorical synthesis: pick the busiest sentence",
    tutor: "Ben, Yale '25",
    durationSec: 280,
    skill: "Writing strategy",
    level: "Intermediate",
    description: "Synthesis questions reward density. The right answer almost always uses every bullet point.",
    thumbnail: "/design/lesson-synthesis.jpg",
    takeaways: [
      "Identify the goal stated in the question stem.",
      "Eliminate any choice that uses only one bullet from the notes.",
      "The right answer usually combines two or more facts to support the stated goal.",
    ],
    transcript: "Rhetorical synthesis questions give you bullet-point notes and ask which sentence best uses them for a stated goal. Watch the choices: short ones that use only one bullet are rarely correct. The right answer is usually the longest, densest one — uses two or three bullets and links them to the goal.",
  },
  {
    id: "act-math-pacing",
    title: "ACT Math: 36 seconds per question",
    tutor: "Anika, Princeton '26",
    durationSec: 260,
    skill: "ACT Math strategy",
    level: "Intermediate",
    description: "60 questions in 60 minutes. The triage system that lets you bank time for the hard ones.",
    thumbnail: "/design/lesson-act-math.jpg",
    takeaways: [
      "Questions 1–30 in 25 minutes — under a minute each.",
      "Questions 31–50 in the next 25 minutes — careful work.",
      "Questions 51–60 in the final 10 minutes — guess on anything past 90 seconds.",
    ],
    transcript: "ACT Math is back-loaded. The first 30 are easy; the last 10 are graduate-level. Rip through 1–30 in 25 minutes, work 31–50 carefully for 25 more, and reserve the final 10 for 51–60. Past 90 seconds without progress on any one question? Guess and move. Points lost from one wrong guess are way fewer than points lost from missing five questions you ran out of time for.",
  },
  {
    id: "act-english-conciseness",
    title: "ACT English: short and right beats long and right",
    tutor: "Ben, Yale '25",
    durationSec: 200,
    skill: "ACT English strategy",
    level: "Beginner",
    description: "The shortest grammatically correct answer wins about 80% of the time on ACT English.",
    thumbnail: "/design/lesson-act-english.jpg",
    takeaways: [
      "When three choices say the same thing in different lengths, pick the shortest grammatical one.",
      "'At this point in time' loses to 'now.' 'Due to the fact that' loses to 'because.'",
      "Conciseness is the most reliable single rule on ACT English.",
    ],
    transcript: "ACT English rewards efficient writing. When you see four choices that say the same thing, the shortest one that's grammatically correct is right roughly 80% of the time. 'At this point in time' loses to 'now.' Even if you're not sure of the grammar rule, picking the short answer is your best default.",
  },
  {
    id: "act-reading-passage-order",
    title: "ACT Reading: which passage to do first",
    tutor: "Ben, Yale '25",
    durationSec: 290,
    skill: "ACT Reading strategy",
    level: "Intermediate",
    description: "The four passages aren't equally hard. Knowing your strongest passage type changes the game.",
    thumbnail: "/design/lesson-act-reading.jpg",
    takeaways: [
      "The four passage types appear in fixed order: Prose Fiction, Social Science, Humanities, Natural Science.",
      "Identify your strongest type from practice tests; do that one first regardless of order.",
      "Banking 2 minutes on your strong passage gives you headroom on your weak one.",
    ],
    transcript: "The ACT Reading passages always come in the same order. Most students do them in order. That's a mistake if your weakest type is first. From practice tests, you'll know your strongest type — start there. Bank 2–3 minutes on the strong passage and you'll have time to be careful on your weakest type.",
  },
  {
    id: "act-science-charts",
    title: "ACT Science: it's not actually a science test",
    tutor: "Anika, Princeton '26",
    durationSec: 270,
    skill: "ACT Science strategy",
    level: "Beginner",
    description: "80% of questions are answerable from charts alone. Here's the order.",
    thumbnail: "/design/lesson-act-science-2.jpg",
    takeaways: [
      "Read the question first. Find the variable.",
      "Locate the chart with that variable. Skip the prose entirely.",
      "Only read prose for conflicting-viewpoints passages and experimental design questions.",
    ],
    transcript: "ACT Science punishes careful readers. Most questions reference one chart and one variable. Read the question, find the chart, match the relationship — linear, inverse, asymptote. The prose is decoration except for two question types: conflicting viewpoints and 'what was the control variable.' For those, you read.",
  },
  {
    id: "ap-calc-frq",
    title: "AP Calculus: the FRQ archetypes",
    tutor: "Anika, Princeton '26",
    durationSec: 380,
    skill: "AP Calculus",
    level: "Advanced",
    description: "Six question patterns appear on every AP Calc FRQ section. Drill by archetype, not chronologically.",
    thumbnail: "/design/lesson-ap-calc.jpg",
    takeaways: [
      "Rate-in/rate-out, particle motion, implicit differentiation, related rates, Riemann sums, differential equations.",
      "Practice 5 of each archetype before practicing whole exams.",
      "Always write units on numerical answers — half a point each, four times.",
    ],
    transcript: "Every AP Calc FRQ section is six questions, and every question is one of six archetypes: rate-in/rate-out, particle motion, implicit differentiation, related rates, Riemann sums, and differential equations. Drill by archetype, not chronologically. Once you've seen 30 FRQs across 5 years, you've seen every variant. Most-missed point: write units on every answer.",
  },
  {
    id: "ap-stats-conditions",
    title: "AP Stats FRQs: the conditions trap",
    tutor: "Anika, Princeton '26",
    durationSec: 250,
    skill: "AP Statistics",
    level: "Intermediate",
    description: "Stating conditions earns easy points — but only if you actually state them, in context.",
    thumbnail: "/design/lesson-ap-stats.jpg",
    takeaways: [
      "Always name three conditions: random, independent, sample size.",
      "Verify each one with the actual numbers from the problem.",
      "Writing 'conditions met' without naming them gets zero points.",
    ],
    transcript: "Conditions are free points on AP Stats FRQs, but most students throw them away. Graders want three things named explicitly. 'Random sample: stated.' 'Independence: 50 < 10% of population.' 'Sample size: np = 35 ≥ 10 and n(1−p) = 15 ≥ 10.' Three sentences. Three points. Don't write 'conditions met' — that's worth nothing.",
  },
  {
    id: "essay-revision",
    title: "Personal statement: revision in three passes",
    tutor: "Daniela, Stanford '24",
    durationSec: 340,
    skill: "Admissions essays",
    level: "Advanced",
    description: "Why the first draft is supposed to be bad — and how to revise without losing your voice.",
    thumbnail: "/design/lesson-essay-revision.jpg",
    takeaways: [
      "Pass 1: structure. Does each paragraph earn its place?",
      "Pass 2: specificity. Replace abstractions with concrete details.",
      "Pass 3: voice. Read it aloud. Cut anything that doesn't sound like you.",
    ],
    transcript: "Three passes, in this order. First, structure: does each paragraph have a job? Cut paragraphs that don't earn their place. Second, specificity: every abstract claim ('I love learning') gets replaced with something concrete. Third, voice: read it aloud. Anything that doesn't sound like you, cut. By draft six, the essay should sound like you on your most articulate day.",
  },
  {
    id: "essay-supplements",
    title: "Why-us essays: the two-specifics rule",
    tutor: "Daniela, Stanford '24",
    durationSec: 310,
    skill: "Admissions essays",
    level: "Advanced",
    description: "The 'why us' supplement separates strong applicants from generic ones. Two specifics, both explained.",
    thumbnail: "/design/lesson-supplements.jpg",
    takeaways: [
      "Name two specific things at the school — a program, a professor, a tradition.",
      "For each, explain why it matters to you specifically.",
      "Avoid name-dropping rankings, prestige, or general majors.",
    ],
    transcript: "Why-us essays are pass-fail. Either you've done your homework or you haven't. Two specifics, both explained. 'I want to study urban planning at [school] because [specific seminar with this professor] is the only place the question of zoning history gets taught seriously, and [student-run advocacy group] would let me practice the policy work I'm already doing.' Two specifics, each tied to your actual life. That's the whole template.",
  },
  {
    id: "interview-prep",
    title: "Alumni interviews: the three-sentence answer",
    tutor: "Daniela, Stanford '24",
    durationSec: 230,
    skill: "Admissions interviews",
    level: "Beginner",
    description: "Most interviews are six predictable questions. A three-sentence frame keeps your answers tight.",
    thumbnail: "/design/lesson-interview.jpg",
    takeaways: [
      "Sentence 1: a specific concrete fact about you.",
      "Sentence 2: a small story or moment.",
      "Sentence 3: what it taught you, in one sentence.",
    ],
    transcript: "Interviewers ask the same six questions. The frame is three sentences. First, a specific fact: 'I run the school newspaper.' Not 'I'm passionate about journalism.' Second, a moment: 'Last spring we ran a story that drew complaints from the principal.' Third, what it taught you: 'It taught me local reporting can change institutional decisions.' Three sentences. Don't ramble.",
  },
];
